apiVersion: v1
kind: Service
metadata:
  name: rscm-api-service
spec:
  selector:
    app: rscm-api-webserver

  type: NodePort
  ports:
    - name: http
      port: 5001
      targetPort: 80
    - name: https
      port: 443
      targetPort: 5001