apiVersion: apps/v1
kind: Deployment
metadata:
  name: rscm-api-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rscm-api-webserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rscm-api-webserver
    spec:
      containers:
      - name: rscm-api-webserver
        image: caiocfer/rscm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /.status
            port: 5001