apiVersion: apps/v1
kind: Deployment
metadata:
  name: rscm-api-webserver
spec:
  selector:
    matchLabels:
      app: rscm-api-webserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rscm-api-webserver
    spec:
      containers:
      - name: rscm-api-webserver
        image: caiocfer/rscm:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /.status
            port: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: rscm-api-service
spec:
  selector:
    app: rscm-api-webserver

  type: NodePort
  ports:
    - name: http
      port: 5001
      targetPort: 80
    - name: https
      port: 443
      targetPort: 5001
    
